version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: in4391-2018-team17-server
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "5005:5005"
    networks:
      - ds-nw
networks:
  ds-nw: